### ISSUE TITLE
[Bug] unsafe eval

### ISSUE THREAD

**Issue by ChenYFan** [mue/mue#201] opened 2021-10-28 02:27 UTC
**Description**
When I used the "custom javascript",it doesn't work,and the dev console had throw out a err msg:

```
Failed to run custom JS:  EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://api.bing.com https://www.google.com".
```

ver 5.3.3
chrome 94
lang zh-cn

I think that using eval was a bad idea.I prefered that establishing a new `<script>`  label.

**Comment by davidcralph** [comment] 2021-11-07 19:51
Hello,

I apologise, but I am not sure of how to fix this. The old method of script label doesn't work for me and I cannot get the custom JS feature working with the Content Security Policy on the extension.

I'm going to disable the custom JS feature on the extension (so it is only available on the web version), and leave this issue open in case anyone wants to try and fix it. If you want to continue using the feature for now I advise you set your homepage to either demo.muetab.com or a built copy of Mue on your computer instead (all features available on the extension work on the web version as well).

**Comment by Wessel** [comment] 2024-02-08 13:08
Closing this issue due to its age and inability to reproduce at current branch

**Closed by Wessel** 2024-02-08 13:08 UTC
Labels: bug, help wanted
