### ISSUE TITLE
[Bug] mue is saving settings per firefox-container

### ISSUE THREAD

**Issue by KAGEYAM4** [mue/mue#893] opened 2024-10-12 13:00 UTC
### Description

Firefox has a feature named multi-account-container. Mue is storing settings per container. Although i  would consider this feature as able to customize per container is awesome. But wanted to let you know. 

Maybe add a option where settings can be imported from different containers. This way avoiding having to build the settings from scratch.

Well i definately consider this a feature.

### Version

7.1.2

### What browser(s) are you seeing the problem on?

Mozilla Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eartharoid** [comment] 2024-10-12 14:50
This is expected as Mue behaves more like a website than an extension, so containers have the same effect on Mue as installing it in a new browser/profile.
This may change in the future as we are looking into cross-browser sync, which could also apply to containers depending on the methods we choose.

**Comment by KAGEYAM4** [comment] 2024-10-12 14:51
> This is expected as Mue behaves more like a website than an extension, so containers have the same effect on Mue as installing it in a new browser/profile. This may change in the future as we are looking into cross-browser sync, which could also apply to containers depending on the methods we choose.

If it would be possible, please let this feature stay. It gives option to customize firefox per container.

**Comment by davidcralph** [comment] 2024-10-13 17:46
Closing as this is a duplicate of #157, but we will be sure to notify you if this gets implemented!

**Closed by davidcralph** 2024-10-13 17:46 UTC
Labels: duplicate, enhancement
